background {
    path = /home/charlie/.files/bg.jpg
    blur_passes = 2
    blur_size = 4
}

input-field {
    size = 300, 50
    outline_thickness = 2
    outer_color = rgb(33ccff)
    inner_color = rgb(000000)
    font_color = rgb(ffffff)
    placeholder_text = <i>Password</i>
    hide_input = false
}
